#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Getopt::Long qw(:config bundling no_ignore_case auto_help auto_version);
use Test::Rinci;

my %opts = (
    include_packages => [],
    include_functions => [],
    exclude_packages => [],
    exclude_functions => [],
    wrap_function => 1,
    test_function_examples => 1,
);
GetOptions(
    '<>' => sub {
        push @{ $opts{include_packages} }, $_[0];
    },
    'exclude-package=s' => $opts{exclude_packages},
    'exclude-function=s' => $opts{exclude_functions},
    'W' => sub { $opts{wrap_function} = 0 },
    'E' => sub { $opts{test_function_examples} = 0 },
);

metadata_in_all_modules_ok(
    \%opts,
);

1;
# ABSTRACT: Test Rinci metadata in all dist's modules
# PODNAME:

=head1 SYNOPSIS

In your dist directory:

 % test-rinci [options] [module]...

To test certain modules only:

 % test-rinci Module1 Module2::Sub

For more options, see documentation.


=head1 DESCRIPTION

This script is an command-line interface for L<Test::Rinci>'s
C<metadata_in_all_modules_ok()> function.


=head1 OPTIONS

=over

=item * --exclude-package=s

Exclude a package. Can be specified multiple times.

=item * --exclude-function=s

Exclude a function. Can be specified multiple times.

=item * -E

This sets C<test_function_examples> to 0.

=item * -W

This sets C<wrap_function> to 0.

=back


=head1 SEE ALSO

L<Test::Rinci>

=cut
